### ISSUE TITLE
Checkpoint release

### ISSUE THREAD

**Issue by JACKHAHA363** [facebookresearch/moco-v3#10]
Hi,

are you going to release the checkpoints?

**Comment by endernewton** [comment]
We have released the pre-trained models at https://github.com/facebookresearch/moco-v3/blob/main/CONFIG.md. Let us know if you think some important ones are missing.

**Comment by eliahuhorwitz** [comment]
> We have released the pre-trained models at https://github.com/facebookresearch/moco-v3/blob/main/CONFIG.md. Let us know if you think some important ones are missing.

Could you please add the checkpoints for the fine-tuned ViT-Base model?
