### ISSUE TITLE
Fine-tuning vs Linear probing

### ISSUE THREAD

**Issue by zhangdan8962** [facebookresearch/moco-v3#21]
Hi,

I am wondering why there is a significant performance gap between Fine-tuning and Linear probing? Additionally,
why the fine-tuning is not used for ResNet model?

Thank you in advance!

**Comment by endernewton** [comment]
There is a difference. Usually fine-tuning end-to-end yields better results.

We did not experiment fine-tuning with ResNet as this is not the focus of our paper. But it is definitely doable.
