### ISSUE TITLE
ViT-Small model number of heads in attention differs from the original paper

### ISSUE THREAD

**Issue by YellowPig-zp** [facebookresearch/moco-v3#7]
Per the DeiT paper and timm's implementation, ViT-S uses 6 heads in the attention blocks. It seems the ViT-S here uses 12 heads. Is there a reason the number of heads is doubled?

**Comment by endernewton** [comment]
We empirically found 12-head ViT-S works better than 6-head, with the same computation. Thus the decision. DEiT folks have also confirmed a similar observation later.
