### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by wildphoton** [facebookresearch/moco-v3#8]
Thank you for open source the Pytorch implementation. I wonder if the original tensorflow implementation have been released for the purpose of training on TPUs.

**Comment by endernewton** [comment]
We have not released and there is no plan to release the code.

**Comment by endernewton** [comment]
The mmf team (https://github.com/facebookresearch/mmf), specifically @ronghanghu have a good implementation of MoCo v3 using PyTorch XLA, which could be a good starting point on TPUs. Maybe good to check about their plan for releasing it.

**Comment by wildphoton** [comment]
Thanks!

**Comment by ronghanghu** [comment]
@wildphoton We have an implementation of MoCo v3 for TPUs here: https://github.com/ronghanghu/simclr_vit_profiling/tree/mocov3_vit_release

**Comment by ronghanghu** [comment]
@wildphoton I can share with you a copy of our TPU implementation if you are interested.

**Comment by wildphoton** [comment]
> @wildphoton I can share with you a copy of our TPU implementation w/ PyTorch XLA if you are interested.

Sure. It would be great to have access to it!

**Comment by MukundVarmaT** [comment]
hi @ronghanghu @wildphoton, 
Can you please share the TPU implementation w/ torch xla? If it's already hosted on a different repo, could you please point me to the same? 

Thanks in advance.

**Comment by ronghanghu** [comment]
@MukundVarmaT it's in https://github.com/ronghanghu/simclr_vit_profiling/tree/mocov3_vit_release
